import Head from 'next/head'
import Header from '@/components/Header'
import Navbar from '../components/Navbar'
import { NextPage } from 'next'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
    </div >
  )
}

export default Home
